# Generated by Django 6.0 on 2026-07-20 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('hero_image', 'Hero Cover Image'), ('infographic', 'Infographic Diagram'), ('social_graphic', 'Social Media Card'), ('youtube_thumbnail', 'YouTube Thumbnail')], default='hero_image', max_length=30)),
                ('prompt', models.TextField(help_text='Detailed AI image generation prompt')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='generated_media/')),
                ('svg_content', models.TextField(blank=True, help_text='Generated SVG diagram code')),
                ('alt_text', models.CharField(max_length=300)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='editorial.editorialarticle')),
            ],
        ),
    ]
