from django.db import models
from django.utils import timezone


class TrendTopic(models.Model):
    """Stores discovered technology trends and their intelligence scores."""
    
    STATUS_CHOICES = [
        ('discovered', 'Discovered'),
        ('prioritized', 'Prioritized'),
        ('researching', 'Researching'),
        ('approved_for_article', 'Approved for Article'),
        ('rejected', 'Rejected'),
        ('archived', 'Archived'),
    ]

    title = models.CharField(max_length=300)
    summary = models.TextField()
    keywords = models.JSONField(default=list, help_text="Extracted technology keywords")
    source = models.CharField(max_length=100, help_text="e.g. Hacker News, GitHub Trending, Product Hunt, RSS")
    source_url = models.URLField(max_length=500, blank=True, null=True)
    category = models.CharField(max_length=100, default="Artificial Intelligence")
    
    # Discovery metrics (Module 1)
    popularity_score = models.FloatField(default=0.0, help_text="Normalized 0-10 score")
    growth_velocity = models.FloatField(default=0.0, help_text="Rate of mention growth")
    future_potential = models.FloatField(default=0.0, help_text="Predicted long-term relevance")
    confidence_score = models.FloatField(default=0.8, help_text="Source trustworthiness score")
    
    # Trend Intelligence Agent scores (Module 2)
    novelty_score = models.FloatField(default=0.0)
    business_relevance_score = models.FloatField(default=0.0)
    african_relevance_score = models.FloatField(default=0.0)
    developer_interest_score = models.FloatField(default=0.0)
    virality_score = models.FloatField(default=0.0)
    priority_score = models.FloatField(default=0.0, db_index=True, help_text="Weighted final decision score")
    
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='discovered')
    raw_data = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-priority_score', '-created_at']
        indexes = [
            models.Index(fields=['status', '-priority_score']),
            models.Index(fields=['category']),
        ]

    def __str__(self):
        return f"{self.title} (Priority: {self.priority_score:.1f})"


class CompetitorSource(models.Model):
    """Monitors competitor publication channels for gap analysis (Module 14)."""
    name = models.CharField(max_length=150)
    site_url = models.URLField(max_length=500)
    feed_url = models.URLField(max_length=500, blank=True, null=True)
    category = models.CharField(max_length=100, default="AI & Tech Media")
    is_active = models.BooleanField(default=True)
    last_scraped_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class CompetitorArticle(models.Model):
    """Stores scraped competitor headlines for gap analysis."""
    competitor = models.ForeignKey(CompetitorSource, on_delete=models.CASCADE, related_name='articles')
    title = models.CharField(max_length=300)
    url = models.URLField(max_length=500, unique=True)
    summary = models.TextField(blank=True)
    published_at = models.DateTimeField(default=timezone.now)
    content_gap_score = models.FloatField(default=0.0, help_text="Opportunity score for Teklora")

    class Meta:
        ordering = ['-published_at']

    def __str__(self):
        return f"[{self.competitor.name}] {self.title}"


class TrendPrediction(models.Model):
    """Stores forecasted trend reports generated by Trend Prediction Agent (Module 15)."""
    TIMEFRAME_CHOICES = [
        ('next_month', 'Next Month'),
        ('next_quarter', 'Next Quarter'),
        ('next_year', 'Next Year'),
    ]

    topic_name = models.CharField(max_length=200)
    category = models.CharField(max_length=100)
    timeframe = models.CharField(max_length=20, choices=TIMEFRAME_CHOICES, default='next_quarter')
    confidence_score = models.FloatField(default=0.7)
    evidence_signals = models.JSONField(default=dict, help_text="GitHub stars, VC signals, search volume data")
    prediction_report = models.TextField(help_text="Detailed AI forecasting report")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-confidence_score', '-created_at']

    def __str__(self):
        return f"{self.topic_name} ({self.timeframe})"
