# Generated by Django 6.0 on 2026-07-20 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackLoopRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('top_performing_topics', models.JSONField(default=list)),
                ('top_performing_headlines', models.JSONField(default=list)),
                ('recommended_priority_boost', models.FloatField(default=1.2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=35.0, help_text='Percentage')),
                ('avg_reading_time_seconds', models.PositiveIntegerField(default=240)),
                ('ctr', models.FloatField(default=4.5, help_text='Click-through rate %')),
                ('social_shares', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('engagement_score', models.FloatField(default=7.5, help_text='Aggregated performance 0-10')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='editorial.editorialarticle')),
            ],
        ),
    ]
