# Generated by Django 5.2.7 on 2026-07-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("manage_blog", "Manage blog posts"),
                    ("publish_blog", "Publish blog posts"),
                    ("manage_projects", "Manage projects"),
                    ("manage_appointments", "Manage appointments"),
                    ("view_inbox", "View inbox"),
                    ("handle_inquiries", "Reply to and archive inquiries"),
                    ("manage_templates", "Manage email templates"),
                    ("manage_campaigns", "Create and edit campaigns"),
                    ("manage_recipients", "Manage campaign recipients"),
                    ("send_campaigns", "Send campaigns"),
                    ("manage_staff", "Manage staff and roles"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
