# Generated by Django 5.2.7 on 2026-07-21 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("staff", "0004_staffinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("invite_sent", "Invitation sent"),
                    ("invite_resent", "Invitation resent"),
                    ("invite_send_failed", "Invitation email failed"),
                    ("invite_revoked", "Invitation revoked"),
                    ("invite_accepted", "Invitation accepted"),
                    ("roles_changed", "Roles changed"),
                    ("user_deactivated", "Account deactivated"),
                    ("user_reactivated", "Account reactivated"),
                    ("group_created", "Role created"),
                    ("group_updated", "Role updated"),
                    ("group_deleted", "Role deleted"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="staffinvitation",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="staffinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("accepted_at__isnull", True)),
                fields=("email",),
                name="unique_pending_invitation_email",
            ),
        ),
    ]
