# Generated by Django 5.2.7 on 2026-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0007_grant_manage_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffinvitation",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
