# Generated by Django 5.2.7 on 2026-09-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_staffinvitation_last_sent_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffcapability",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("manage_blog", "Manage blog posts"),
                    ("publish_blog", "Publish blog posts"),
                    ("manage_projects", "Manage projects"),
                    ("manage_appointments", "Manage appointments"),
                    ("view_inbox", "View inbox"),
                    ("handle_inquiries", "Reply to and archive inquiries"),
                    ("manage_templates", "Manage email templates"),
                    ("manage_campaigns", "Create and edit campaigns"),
                    ("manage_recipients", "Manage campaign recipients"),
                    ("send_campaigns", "Send campaigns"),
                    ("manage_tasks", "Assign and review tasks"),
                    ("manage_staff", "Manage staff and roles"),
                    ("receive_alerts", "Receive system health alerts"),
                ],
            },
        ),
    ]
