# Generated by Django 5.2.7 on 2026-09-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0011_staffprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("invite_sent", "Invitation sent"),
                    ("invite_resent", "Invitation resent"),
                    ("invite_send_failed", "Invitation email failed"),
                    ("invite_revoked", "Invitation revoked"),
                    ("invite_accepted", "Invitation accepted"),
                    ("roles_changed", "Roles changed"),
                    ("user_deactivated", "Account deactivated"),
                    ("user_reactivated", "Account reactivated"),
                    ("group_created", "Role created"),
                    ("group_updated", "Role updated"),
                    ("group_deleted", "Role deleted"),
                    ("handle_chosen", "Work address chosen"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
