# Generated by Django 5.2.7 on 2026-09-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0014_grant_view_all_mail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffcapability",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("manage_blog", "Manage blog posts"),
                    ("publish_blog", "Publish blog posts"),
                    ("manage_projects", "Manage projects"),
                    ("manage_appointments", "Manage appointments"),
                    ("view_inbox", "View inbox"),
                    ("view_all_mail", "Read every staff mailbox"),
                    ("manage_mail_limits", "Set mail sending limits"),
                    ("handle_inquiries", "Reply to and archive inquiries"),
                    ("manage_templates", "Manage email templates"),
                    ("manage_campaigns", "Create and edit campaigns"),
                    ("manage_recipients", "Manage campaign recipients"),
                    ("send_campaigns", "Send campaigns"),
                    ("manage_tasks", "Assign and review tasks"),
                    ("manage_staff", "Manage staff and roles"),
                    ("receive_alerts", "Receive system health alerts"),
                ],
            },
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="daily_mail_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("invite_sent", "Invitation sent"),
                    ("invite_resent", "Invitation resent"),
                    ("invite_send_failed", "Invitation email failed"),
                    ("invite_revoked", "Invitation revoked"),
                    ("invite_accepted", "Invitation accepted"),
                    ("roles_changed", "Roles changed"),
                    ("user_deactivated", "Account deactivated"),
                    ("user_reactivated", "Account reactivated"),
                    ("group_created", "Role created"),
                    ("group_updated", "Role updated"),
                    ("group_deleted", "Role deleted"),
                    ("handle_chosen", "Work address chosen"),
                    ("mail_limit_changed", "Mail sending limit changed"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
