# Generated by Django 5.2.7 on 2026-10-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0016_grant_manage_mail_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="coding_languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of programming languages, e.g. ['Python', 'TypeScript']",
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="frameworks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of frameworks & tools, e.g. ['Django', 'React', 'Docker']",
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="github_username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="is_onboarded",
            field=models.BooleanField(
                default=False,
                help_text="True when the staff member has completed capabilities & WhatsApp onboarding.",
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="primary_role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Fullstack Engineer, Backend Developer, AI / ML Engineer, DevOps",
                max_length=64,
            ),
        ),
    ]
