# Generated by Django 5.2.7 on 2026-04-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_update_embedding_dimensions'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogpost',
            name='brand_blogpost_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='brand_blogpost_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='brand_blogpost_featured_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='brand_blogpost_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='brand_event_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='brand_event_featured_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='brand_event_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='brand_project_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='brand_project_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='brand_project_featured_idx',
        ),
    ]
