# Generated by Django 5.2.7 on 2026-04-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_remove_blogpost_brand_blogpost_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commit_count',
            field=models.IntegerField(blank=True, default=0, help_text='Total number of commits', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_id',
            field=models.IntegerField(blank=True, help_text='Unique ID from GitHub', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_role',
            field=models.CharField(blank=True, help_text="User's role (e.g., owner, collaborator)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_github_synced',
            field=models.BooleanField(default=False, help_text='True if this project was auto-populated from GitHub'),
        ),
        migrations.AddField(
            model_name='project',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When the repository was last synced', null=True),
        ),
    ]
