# Generated by Django 5.2.7 on 2026-07-21 08:21

from django.db import migrations, models


def publish_existing_posts(apps, schema_editor):
    """Every post that existed before this field was added was live.

    The field defaults to 'draft' for new posts, so without this backfill the
    migration would hide the entire public blog.
    """
    BlogPost = apps.get_model("brand", "BlogPost")
    BlogPost.objects.update(status="published")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0009_add_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
        migrations.RunPython(publish_existing_posts, noop),
    ]
