# Generated by Django 5.2.7 on 2026-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_project_commit_count_project_github_repo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readme_content',
            field=models.TextField(blank=True, help_text='Raw Markdown README from GitHub', null=True),
        ),
    ]
