# Generated by Django 5.2.7 on 2026-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_add_readme_content_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cached_commits',
            field=models.JSONField(blank=True, help_text='Last 10 commits cached during sync', null=True),
        ),
    ]
