# Generated by Django 6.0 on 2026-07-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_blogpost_status'),
        ('brand', '0011_add_cached_commits_to_project'),
    ]

    operations = [
    ]
