# Generated by Django 6.0 on 2026-07-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_blogcomment_bloglike'),
        ('brand', '0012_merge_20260722_1318'),
    ]

    operations = [
    ]
