# Generated by Django 5.2.7 on 2026-09-21 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0013_merge_20260727_0036"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="accent",
            field=models.CharField(
                default="#00FF94",
                help_text="Hex accent for text and icons.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="accent_deep",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hex for badge fills and borders. Defaults to the accent.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="badge_icon",
            field=models.CharField(
                blank=True,
                default="fas fa-check-circle",
                help_text="Full Font Awesome classes, e.g. 'fab fa-whatsapp'.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="badge_label",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="project",
            name="card_variant",
            field=models.CharField(
                choices=[
                    ("default", "Standard card"),
                    ("spotlight", "Spotlight (gradient, glow, taller gallery)"),
                ],
                default="default",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="chart_heading",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="project",
            name="chart_icon",
            field=models.CharField(
                blank=True, default="fas fa-chart-bar", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="chart_spec",
            field=models.JSONField(
                blank=True,
                help_text="Chart.js config: {type, data, options}.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cta_icon",
            field=models.CharField(
                blank=True, default="fas fa-external-link-alt", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cta_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Button text. Blank hides the button; the link is project_url.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Position within its phase. Lower sorts first."
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="features_heading",
            field=models.CharField(
                blank=True, default="Core Capabilities & Modules", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gallery_heading",
            field=models.CharField(
                blank=True, default="Interface Gallery", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase",
            field=models.CharField(
                choices=[
                    ("completed", "Completed & Live"),
                    ("active", "Active Development"),
                    ("future", "Future Vision"),
                ],
                default="completed",
                help_text="Which /products/ group this appears under.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="showcase",
            field=models.BooleanField(
                default=False,
                help_text="Show this project as a full article on /products/.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Anchor id on /products/ (e.g. 'edushare'), so deep links keep working.",
                max_length=220,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="style_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ProjectFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("card", "Boxed row with icon and bold label"),
                            ("chip", "Compact chip"),
                            ("check", "Plain check line"),
                        ],
                        default="card",
                        max_length=10,
                    ),
                ),
                ("icon", models.CharField(blank=True, default="", max_length=60)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bolded lead-in, card style only.",
                        max_length=120,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="brand.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="project_gallery/"
                    ),
                ),
                (
                    "static_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path under static/, e.g. 'brand/images/edushare.png'.",
                        max_length=300,
                    ),
                ),
                ("remote_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "full_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Larger render for the lightbox. Defaults to the tile image.",
                        max_length=500,
                    ),
                ),
                ("alt", models.CharField(blank=True, default="", max_length=200)),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Shown on hover, after 'Expand Mockup N:'.",
                        max_length=200,
                    ),
                ),
                (
                    "lightbox_title",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="brand.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=120)),
                ("body", models.TextField(blank=True, default="")),
                ("icon", models.CharField(blank=True, default="", max_length=60)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hex for the heading, e.g. '#F87171'. Blank uses the accent.",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="brand.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
