# Generated by Django 5.2

import brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0013_merge_20260727_0036"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ("brand_name", models.CharField(default="Teklora", max_length=100)),
                ("logo_url", models.CharField(default="/static/brand/images/logo.png", max_length=500)),
                ("header_links", models.JSONField(default=brand.models.default_header_links)),
                ("header_cta_label", models.CharField(default="Book Strategy Consultation", max_length=100)),
                ("header_cta_url", models.CharField(default="/contacts/#book", max_length=500)),
                ("footer_description", models.TextField(default="Innovative technology solutions for modern businesses.")),
                ("footer_quick_heading", models.CharField(default="Quick Links", max_length=100)),
                ("footer_services_heading", models.CharField(default="Services", max_length=100)),
                ("footer_contact_heading", models.CharField(default="Contact", max_length=100)),
                ("footer_quick_links", models.JSONField(default=brand.models.default_footer_quick_links)),
                ("footer_services", models.JSONField(default=brand.models.default_footer_services)),
                ("footer_legal_links", models.JSONField(default=brand.models.default_footer_legal_links)),
                ("footer_social_links", models.JSONField(default=brand.models.default_footer_social_links)),
                ("contact_email", models.EmailField(default="teklorasolutionsltd@gmail.com", max_length=254)),
                ("contact_phone", models.CharField(default="+254 704 894220", max_length=50)),
                ("copyright_text", models.CharField(default="© 2026 Teklora Solutions. All rights reserved.", max_length=200)),
                ("landing_title", models.CharField(default="Teklora - Building Technology That Leaves a Lasting Legacy Across Africa", max_length=200)),
                ("landing_meta_description", models.TextField(default="Teklora is a Kenyan technology company engineering custom software, cloud engines, and AI platforms built to transform businesses, universities, NGOs, and institutions across Africa.")),
                ("hero_title_before", models.CharField(default="Building Technology That Leaves a ", max_length=180)),
                ("hero_title_highlight", models.CharField(default="Lasting Legacy", max_length=120)),
                ("hero_title_after", models.CharField(default=" Across Africa", max_length=120)),
                ("hero_description", models.TextField(default="We don't just build websites. We engineer scalable software products, cloud platforms, and intelligent systems that solve real African challenges and empower institutions to lead.")),
                ("hero_quote", models.CharField(default="Building technology that leaves a lasting legacy across Africa.", max_length=300)),
                ("hero_primary_label", models.CharField(default="Book an Appointment", max_length=100)),
                ("hero_primary_url", models.CharField(default="/contacts/#book", max_length=500)),
                ("hero_secondary_label", models.CharField(default="Explore EduShare Flagship", max_length=100)),
                ("hero_secondary_url", models.CharField(default="#flagship-edushare", max_length=500)),
                ("hero_image_url", models.CharField(default="/static/brand/images/HEROO.png", max_length=500)),
                ("hero_scroll_label", models.CharField(default="Discover Our Vision", max_length=100)),
                ("story_label", models.CharField(default="Our Story & Purpose", max_length=100)),
                ("story_heading", models.CharField(default="Africa Deserves Technology Built for African Challenges", max_length=250)),
                ("story_tabs", models.JSONField(default=brand.models.default_story_tabs)),
                ("flagship_label", models.CharField(default="Flagship Innovation Spotlight", max_length=120)),
                ("flagship_title", models.CharField(default="EduShare Africa", max_length=160)),
                ("flagship_description", models.TextField(default="Proof of Teklora's capability to build scalable, high-impact technology products that transform African education.")),
                ("flagship_image_url", models.CharField(default="/static/brand/images/edushare.png", max_length=500)),
                ("capabilities_label", models.CharField(default="Technical Capabilities", max_length=120)),
                ("capabilities_heading", models.CharField(default="Services Delivered as Scalable Solutions", max_length=250)),
                ("capabilities_description", models.TextField(default="Explore our specialized technology solutions engineered for maximum performance, security, and continental scale.")),
                ("technology_label", models.CharField(default="Core Tech Stack", max_length=120)),
                ("technology_heading", models.CharField(default="Technology We Build With", max_length=200)),
                ("technology_description", models.TextField(default="We rely on a battle-tested Python and React stack engineered for security, speed, and massive scale.")),
                ("why_label", models.CharField(default="Why Teklora", max_length=100)),
                ("why_heading", models.CharField(default="We engineer long-term, scalable technology products built for continental impact, not short-term dev hand-offs.", max_length=300)),
                ("journey_label", models.CharField(default="Execution Method", max_length=100)),
                ("journey_heading", models.CharField(default="Our Engineering Journey", max_length=200)),
                ("journey_description", models.CharField(default="Hover over any stage below to explore our structured execution framework.", max_length=300)),
                ("impact_label", models.CharField(default="Impact in Numbers", max_length=100)),
                ("impact_heading", models.CharField(default="Our Track Record Across Africa", max_length=200)),
            ],
            options={
                "verbose_name": "site content",
                "verbose_name_plural": "site content",
            },
        ),
    ]
