"""
Django settings for brandtechsolution project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================
# SECURITY & ENVIRONMENT
# ============================================================

# IMPORTANT:
# In production, set this in EC2:
# export DEBUG=False
# export SECRET_KEY="your-secret-key"
# export EMAIL_HOST_USER="your-email@gmail.com"
# export EMAIL_HOST_PASSWORD="your-app-password"

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-qle-bmx+6%6qe81&hck$q%+%8($+n4z9-4d7=!4v!0ce75-vjv"
)

DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

# Production hosts
PRODUCTION_ALLOWED_HOSTS = [
    "brantechsolutions.co",
    "www.brantechsolutions.co",
    "16.171.7.205",
    "127.0.0.1",
    "localhost",
]

# Development hosts
DEVELOPMENT_ALLOWED_HOSTS = ["*"]

ALLOWED_HOSTS = PRODUCTION_ALLOWED_HOSTS if not DEBUG else DEVELOPMENT_ALLOWED_HOSTS

# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'brand',
    'appointments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'brandtechsolution.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'brandtechsolution.wsgi.application'

# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ============================================================
# STATIC & MEDIA FILES
# ============================================================

STATIC_URL = '/static/'

# Local environment
LOCAL_STATIC_ROOT = BASE_DIR / "staticfiles"
LOCAL_MEDIA_ROOT = BASE_DIR / "media"

# EC2 production paths
PRODUCTION_STATIC_ROOT = "/var/www/brandtech/static"
PRODUCTION_MEDIA_ROOT = "/var/www/brandtech/media"

STATICFILES_DIRS = [
    BASE_DIR / 'brand' / 'static',
]

STATIC_ROOT = PRODUCTION_STATIC_ROOT if not DEBUG else LOCAL_STATIC_ROOT
MEDIA_ROOT = PRODUCTION_MEDIA_ROOT if not DEBUG else LOCAL_MEDIA_ROOT
MEDIA_URL = '/media/'

# ============================================================
# EMAIL SETTINGS
# ============================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ============================================================
# AUTHENTICATION REDIRECTS
# ============================================================

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ============================================================
# DEFAULT PRIMARY KEY FIELD
# ============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
