"""
Django settings for brandtechsolution project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
from brandtechsolution.config import config
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================
# SECURITY & ENVIRONMENT
# ============================================================

# IMPORTANT:
# In production, set this in EC2:
# export DEBUG=False
# export SECRET_KEY="your-secret-key"
# export EMAIL_HOST_USER="your-email@gmail.com"
# export EMAIL_HOST_PASSWORD="your-app-password"

SECRET_KEY = config.secret_key

DEBUG = config.debug

# # Production hosts
# PRODUCTION_ALLOWED_HOSTS = [
#     "brantechsolutions.co",
#     "www.brantechsolutions.co",
#     "16.171.7.205",
#     "127.0.0.1",
#     "localhost",
# ]

# # Development hosts
# DEVELOPMENT_ALLOWED_HOSTS = ["*"]

ALLOWED_HOSTS = config.allowed_hosts

# Send X-Content-Type-Options: nosniff on all responses (incl. user-uploaded
# media served via Django) to block MIME-sniffing -> same-origin XSS.
SECURE_CONTENT_TYPE_NOSNIFF = True

# HTTPS origins trusted for CSRF. Behind the Cloudflare Tunnel, TLS terminates
# at the edge and forms POST to https://<domain>; without this Django returns 403.
CSRF_TRUSTED_ORIGINS = config.csrf_trusted_origins

# The tunnel forwards plain HTTP to web:8000 with X-Forwarded-Proto: https.
# Trust it so request.is_secure() correctly reflects the original HTTPS request.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'brand',
    'appointments',
    'ai_workflows',
    'messaging',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # Add response compression
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'brandtechsolution.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'brandtechsolution.wsgi.application'

# ============================================================
# DATABASE
# ============================================================

if config.database_engine.lower() == "postgresql":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config.database_name,
            'USER': config.database_user,
            'PASSWORD': config.database_password,
            'HOST': config.database_host,
            'PORT': config.database_port,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Persistent connections (Postgres)
CONN_MAX_AGE = config.database_conn_max_age

# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

# ============================================================
# STATIC & MEDIA FILES
# ============================================================

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'brand' / 'static',
]

# Roots come from config (env-driven); see brandtechsolution/config.py
STATIC_ROOT = config.static_root
MEDIA_ROOT = config.media_root
MEDIA_URL = '/media/'

# WhiteNoise compressed storage for collected static files.
# NOTE: the strict ManifestStaticFilesStorage variant is intentionally NOT used:
# brand/css/styles2.css references a missing asset (brand/css/images/bg.jpg),
# which makes the manifest backend hard-fail collectstatic. CompressedStaticFilesStorage
# still gzip/brotli-compresses static files but tolerates unresolved url() references.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# ============================================================
# EMAIL SETTINGS
# ============================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config.email_host
EMAIL_PORT = config.email_port
EMAIL_USE_TLS = config.email_use_tls
EMAIL_HOST_USER = config.email_host_user
EMAIL_HOST_PASSWORD = config.email_host_password
# Bounds how long a single SMTP send can block. This matters for the outbox
# reaper below: a batch's worst-case send time is roughly
# OUTBOX_BATCH_SIZE * EMAIL_TIMEOUT seconds, which must stay under
# OUTBOX_STALE_CLAIM_MINUTES * 60 or the reaper may release rows a live run
# is still sending, risking duplicate delivery.
EMAIL_TIMEOUT = config.email_timeout

DEFAULT_FROM_EMAIL = config.email_host_user

OUTBOX_BATCH_SIZE = config.outbox_batch_size
OUTBOX_MAX_ATTEMPTS = config.outbox_max_attempts
OUTBOX_STALE_CLAIM_MINUTES = config.outbox_stale_claim_minutes
SITE_BASE_URL = config.site_base_url

# ============================================================
# AUTHENTICATION REDIRECTS
# ============================================================

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ============================================================
# LOGGING CONFIGURATION
# ============================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai_workflows': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'langchain': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'langgraph': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ============================================================
# DEFAULT PRIMARY KEY FIELD
# ============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
