# Generated by Django 6.0 on 2026-07-20 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_concepts', models.JSONField(default=list, help_text='Core concepts and definitions')),
                ('timeline', models.JSONField(default=list, help_text='Historical milestones and developments')),
                ('technical_explanations', models.TextField(help_text='Deep architectural & technical breakdown')),
                ('advantages_and_limitations', models.JSONField(default=dict, help_text='Pros and Cons')),
                ('industry_applications', models.TextField(blank=True, help_text='Global industry use cases')),
                ('african_opportunities', models.TextField(help_text='African ecosystem & startup opportunities')),
                ('future_outlook', models.TextField(blank=True)),
                ('sources', models.JSONField(default=list, help_text='List of verified reference URLs and citations')),
                ('structured_dossier', models.TextField(help_text='Complete markdown research dossier')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='trends.trendtopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedFactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_level', models.FloatField(default=0.9, help_text='Overall fact verification score (0-1)')),
                ('contradictions_detected', models.JSONField(default=list, help_text='Identified discrepancies')),
                ('unsupported_claims_removed', models.JSONField(default=list, help_text='Filtered out unverified claims')),
                ('verified_statistics', models.JSONField(default=list, help_text='Cross-referenced statistics')),
                ('verified_quotes', models.JSONField(default=list, help_text='Attributed expert quotes')),
                ('verified_dossier', models.TextField(help_text='Final sanitized and verified research text')),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_report', to='research.researchdossier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
