# Generated by Django 5.2.7 on 2026-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifiedfactreport",
            name="verification_evidence",
            field=models.TextField(
                blank=True,
                default="",
                help_text="What the agent found when it checked the dossier's sources: the tool calls it made and what came back. Separate from verified_dossier because that field is what the writer drafts from, and fetched source text must not reach the article prompt.",
            ),
        ),
    ]
