# Generated by Django 5.2.7 on 2026-09-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_verification_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifiedfactreport",
            name="verified_opportunities",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The dossier's African opportunities section after audit. The writer drafts that section from this, never from the dossier's raw field, or a claim the verifier removed would go straight back into the article.",
            ),
        ),
    ]
