# Generated by Django 6.0 on 2026-07-20 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0009_add_blog_slug'),
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='published', max_length=30)),
                ('channels_notified', models.JSONField(default=list, help_text='List of engines/channels notified e.g. Google, Bing, RSS')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publishing_log', to='editorial.editorialarticle')),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishing_logs', to='brand.blogpost')),
            ],
        ),
    ]
