# Generated by Django 5.2.7 on 2025-11-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_email_appointment_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
    ]
