# Generated by Django 5.2.7 on 2026-04-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_date_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_created_idx',
        ),
    ]
