# Generated by Django 5.2.7 on 2026-08-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    """Drop the unique constraints on Appointment.email and .phone.

    They were the cause of a broken-access-control bug rather than a
    safeguard. Because one email could hold only one appointment,
    create_appointment - a public, unauthenticated endpoint - handled a
    repeat booking by UPDATING the existing row, so submitting a stranger's
    address rewrote their appointment. Repeat bookings are ordinary; the
    constraint was the wrong shape for the table.

    Duplicates are now real rows and staff dedupe them from the appointments
    list.

    NOTE ON REVERSING: the auto-generated backwards operation restores
    unique=True and will fail on any database that has since taken two
    bookings from one address - which is the entire point of this change. To
    roll back, merge or delete the duplicates first.
    """

    dependencies = [
        ("appointments", "0006_remove_appointment_appt_date_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=255, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Phone"
            ),
        ),
    ]
