# Generated by Django 6.0 on 2026-07-20 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_voice', models.TextField(default='Authoritative, forward-looking, technically grounded, African-centric, and accessible.')),
                ('preferred_terminology', models.JSONField(default=dict, help_text="Key dictionary mappings, e.g. {'AI Agent': 'Autonomous AI Agent'}")),
                ('seo_rules', models.JSONField(default=dict)),
                ('excluded_topics', models.JSONField(default=list, help_text='Topics recently covered to avoid repetition')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Editorial Memory',
            },
        ),
        migrations.CreateModel(
            name='EditorialArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('executive_summary', models.TextField()),
                ('hero_paragraph', models.TextField()),
                ('introduction', models.TextField()),
                ('problem_statement', models.TextField()),
                ('historical_context', models.TextField(blank=True)),
                ('current_developments', models.TextField()),
                ('technical_explanation', models.TextField()),
                ('industry_impact', models.TextField()),
                ('african_perspective', models.TextField()),
                ('case_studies', models.TextField(blank=True)),
                ('expert_insights', models.TextField(blank=True)),
                ('future_predictions', models.TextField()),
                ('conclusion', models.TextField()),
                ('call_to_action', models.TextField(default='Subscribe to Teklora Innovation Dispatch for weekly African & Global tech intelligence.')),
                ('faqs', models.JSONField(default=list, help_text='List of QA pairs')),
                ('references', models.JSONField(default=list, help_text='Cited reference links and sources')),
                ('meta_description', models.CharField(max_length=300)),
                ('keywords', models.JSONField(default=list)),
                ('schema_markup', models.JSONField(default=dict)),
                ('internal_linking_suggestions', models.JSONField(default=list)),
                ('external_references', models.JSONField(default=list)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='editorial_heroes/')),
                ('hero_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('hero_image_prompt', models.TextField(blank=True)),
                ('image_alt_text', models.CharField(blank=True, max_length=300)),
                ('target_audience', models.CharField(choices=[('developers', 'Software Engineers & Developers'), ('business_executives', 'Business Leaders & CXOs'), ('african_founders', 'African Startup Founders'), ('investors', 'Tech Investors & VCs'), ('general_tech', 'General Technology Audience')], default='developers', max_length=50)),
                ('tone', models.CharField(default='Analytical & Authoritative', max_length=50)),
                ('reading_time_minutes', models.PositiveIntegerField(default=6)),
                ('estimated_reading_difficulty', models.CharField(default='Intermediate', max_length=50)),
                ('status', models.CharField(choices=[('drafting', 'Drafting'), ('review_pending', 'Pending Editor Approval'), ('approved', 'Approved for Publishing'), ('rejected', 'Rejected by Editor'), ('published', 'Published to Teklora Blog')], db_index=True, default='drafting', max_length=30)),
                ('editor_notes', models.TextField(blank=True, help_text='Notes/feedback from human editor')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='trends.trendtopic')),
                ('verification_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='research.verifiedfactreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_post', models.TextField()),
                ('linkedin_article', models.TextField()),
                ('twitter_thread', models.JSONField(default=list, help_text='List of tweets in thread')),
                ('facebook_post', models.TextField()),
                ('instagram_carousel', models.JSONField(default=list, help_text='Slide titles and bullet captions')),
                ('newsletter', models.TextField(help_text='Email newsletter edition format')),
                ('medium_article', models.TextField()),
                ('devto_article', models.TextField()),
                ('podcast_outline', models.TextField()),
                ('youtube_script', models.TextField()),
                ('tiktok_script', models.TextField()),
                ('executive_summary_one_pager', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_package', to='editorial.editorialarticle')),
            ],
        ),
    ]
