from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from research.models import VerifiedFactReport, TrendTopic


class EditorialArticle(models.Model):
    """Module 6 & 10: Editorial Draft Article

    Holds complete journalism-grade long-form article sections generated by AI Writer Agent
    and routed through Human Approval Workflow before publication.
    """
    STATUS_CHOICES = [
        ('drafting', 'Drafting'),
        ('review_pending', 'Pending Editor Approval'),
        ('approved', 'Approved for Publishing'),
        ('rejected', 'Rejected by Editor'),
        ('published', 'Published to Teklora Blog'),
    ]

    AUDIENCE_CHOICES = [
        ('developers', 'Software Engineers & Developers'),
        ('business_executives', 'Business Leaders & CXOs'),
        ('african_founders', 'African Startup Founders'),
        ('investors', 'Tech Investors & VCs'),
        ('general_tech', 'General Technology Audience'),
    ]

    topic = models.ForeignKey(TrendTopic, on_delete=models.SET_NULL, null=True, blank=True, related_name='articles')
    verification_report = models.OneToOneField(VerifiedFactReport, on_delete=models.SET_NULL, null=True, blank=True, related_name='article')

    # Core Headline & Metadata
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=320, unique=True, blank=True)
    subtitle = models.CharField(max_length=400, blank=True)
    executive_summary = models.TextField()
    hero_paragraph = models.TextField()

    # Article Core Body Sections
    introduction = models.TextField()
    problem_statement = models.TextField()
    historical_context = models.TextField(blank=True)
    current_developments = models.TextField()
    technical_explanation = models.TextField()
    industry_impact = models.TextField()
    african_perspective = models.TextField()
    case_studies = models.TextField(blank=True)
    expert_insights = models.TextField(blank=True)
    future_predictions = models.TextField()
    conclusion = models.TextField()
    
    call_to_action = models.TextField(default="Subscribe to Teklora Innovation Dispatch for weekly African & Global tech intelligence.")
    faqs = models.JSONField(default=list, help_text="List of QA pairs")
    references = models.JSONField(default=list, help_text="Cited reference links and sources")

    # SEO & Metadata (Module 7)
    meta_description = models.CharField(max_length=300)
    keywords = models.JSONField(default=list)
    schema_markup = models.JSONField(default=dict)
    internal_linking_suggestions = models.JSONField(default=list)
    external_references = models.JSONField(default=list)

    # Visuals & Media (Module 8)
    hero_image = models.ImageField(upload_to='editorial_heroes/', blank=True, null=True)
    hero_image_url = models.URLField(max_length=500, blank=True, null=True)
    hero_image_prompt = models.TextField(blank=True)
    image_alt_text = models.CharField(max_length=300, blank=True)

    # Audience & Strategy (Module 5 & 16)
    target_audience = models.CharField(max_length=50, choices=AUDIENCE_CHOICES, default='developers')
    tone = models.CharField(max_length=50, default='Analytical & Authoritative')
    reading_time_minutes = models.PositiveIntegerField(default=6)
    estimated_reading_difficulty = models.CharField(max_length=50, default='Intermediate')

    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='drafting', db_index=True)
    editor_notes = models.TextField(blank=True, help_text="Notes/feedback from human editor")
    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"[{self.get_status_display()}] {self.title}"

    def save(self, *args, **kwargs):
        if not self.slug:
            base = slugify(self.title)[:280] or "teklora-article"
            slug = base
            n = 2
            while EditorialArticle.objects.exclude(pk=self.pk).filter(slug=slug).exists():
                slug = f"{base}-{n}"
                n += 1
            self.slug = slug
        super().save(*args, **kwargs)

    def get_full_markdown_content(self) -> str:
        """Assembles all structured sections into a unified markdown article."""
        parts = [
            f"# {self.title}",
            f"*{self.subtitle}*\n",
            f"**Executive Summary:** {self.executive_summary}\n",
            f"## Introduction\n{self.introduction}\n",
            f"## Problem Statement\n{self.problem_statement}\n",
            f"## Current Developments & Breakthroughs\n{self.current_developments}\n",
            f"## Technical Deep Dive\n{self.technical_explanation}\n",
            f"## Global Industry Impact\n{self.industry_impact}\n",
            f"## African Ecosystem Perspective & Opportunities\n{self.african_perspective}\n",
            f"## Strategic Outlook & Future Predictions\n{self.future_predictions}\n",
            f"## Conclusion\n{self.conclusion}\n",
            f"---\n**Call to Action:** {self.call_to_action}"
        ]
        return "\n\n".join(parts)


class SocialPackage(models.Model):
    """Module 9: Multi-Platform Content Agent Package

    Generates social posts, threads, newsletters, video scripts, and presentation slides
    from a single article.
    """
    article = models.OneToOneField(EditorialArticle, on_delete=models.CASCADE, related_name='social_package')

    linkedin_post = models.TextField()
    linkedin_article = models.TextField()
    twitter_thread = models.JSONField(default=list, help_text="List of tweets in thread")
    facebook_post = models.TextField()
    instagram_carousel = models.JSONField(default=list, help_text="Slide titles and bullet captions")
    
    newsletter = models.TextField(help_text="Email newsletter edition format")
    medium_article = models.TextField()
    devto_article = models.TextField()
    
    podcast_outline = models.TextField()
    youtube_script = models.TextField()
    tiktok_script = models.TextField()
    executive_summary_one_pager = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Social Ecosystem Package for: {self.article.title}"


class EditorialMemory(models.Model):
    """Module 17: Editorial Memory Agent

    Remembers writing guidelines, tone rules, preferred brand vocabulary, and past covered topics.
    """
    brand_voice = models.TextField(default="Authoritative, forward-looking, technically grounded, African-centric, and accessible.")
    preferred_terminology = models.JSONField(default=dict, help_text="Key dictionary mappings, e.g. {'AI Agent': 'Autonomous AI Agent'}")
    seo_rules = models.JSONField(default=dict)
    excluded_topics = models.JSONField(default=list, help_text="Topics recently covered to avoid repetition")
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Editorial Memory"

    def __str__(self):
        return "Teklora Editorial Memory & Guidelines"
