from django.test import TestCase
from django.urls import reverse
from brand.models import BlogPost
from brand.markdown_utils import render_markdown


class BlogSlugTests(TestCase):
    def test_slug_autogenerated_from_title(self):
        post = BlogPost.objects.create(
            title="Getting Started With Agentic AI",
            excerpt="x", content="body",
        )
        self.assertEqual(post.slug, "getting-started-with-agentic-ai")

    def test_slug_collision_gets_numeric_suffix(self):
        BlogPost.objects.create(title="Hello World", excerpt="x", content="b")
        second = BlogPost.objects.create(title="Hello World", excerpt="y", content="b")
        self.assertEqual(second.slug, "hello-world-2")

    def test_existing_slug_preserved_on_title_change(self):
        post = BlogPost.objects.create(title="Original Title", excerpt="x", content="b")
        original_slug = post.slug
        post.title = "Completely Different Title"
        post.save()
        self.assertEqual(post.slug, original_slug)

    def test_blank_title_falls_back_to_post(self):
        post = BlogPost.objects.create(title="!!!", excerpt="x", content="b")
        self.assertEqual(post.slug, "post")


class RenderMarkdownTests(TestCase):
    def test_renders_basic_markdown(self):
        html = render_markdown("# Title\n\nSome **bold** text")
        self.assertIn("<h1>Title</h1>", html)
        self.assertIn("<strong>bold</strong>", html)

    def test_single_newlines_become_breaks(self):
        html = render_markdown("line one\nline two")
        self.assertIn("<br", html)

    def test_strips_script_tags(self):
        html = render_markdown("hello <script>alert('x')</script> world")
        self.assertNotIn("<script>", html)
        self.assertNotIn("alert(", html)

    def test_strips_event_handler_attributes(self):
        html = render_markdown('<img src="x" onerror="alert(1)">')
        self.assertNotIn("onerror", html)

    def test_empty_input_returns_empty_string(self):
        self.assertEqual(render_markdown(""), "")
        self.assertEqual(render_markdown(None), "")


class BlogViewTests(TestCase):
    def setUp(self):
        self.post = BlogPost.objects.create(
            title="Indexable Post",
            excerpt="A short summary.",
            content="# Heading\n\nThe **body** content.",
            category="AI & Machine Learning",
            # Posts now default to draft, and the public views filter those
            # out. These tests are about the published reading experience.
            status="published",
        )

    def test_get_absolute_url(self):
        self.assertEqual(self.post.get_absolute_url(), f"/blog/{self.post.slug}/")

    def test_detail_returns_200_and_renders_content(self):
        resp = self.client.get(f"/blog/{self.post.slug}/")
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Indexable Post")
        self.assertContains(resp, "<strong>body</strong>")

    def test_detail_unknown_slug_404(self):
        resp = self.client.get("/blog/does-not-exist/")
        self.assertEqual(resp.status_code, 404)

    def test_detail_increments_view_count(self):
        before = self.post.view_count
        self.client.get(f"/blog/{self.post.slug}/")
        self.post.refresh_from_db()
        self.assertEqual(self.post.view_count, before + 1)

    def test_list_returns_200_and_links_to_posts(self):
        resp = self.client.get(reverse("blog"))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, self.post.get_absolute_url())
