from django.test import TestCase
from brand.models import BlogPost


class BlogSlugTests(TestCase):
    def test_slug_autogenerated_from_title(self):
        post = BlogPost.objects.create(
            title="Getting Started With Agentic AI",
            excerpt="x", content="body",
        )
        self.assertEqual(post.slug, "getting-started-with-agentic-ai")

    def test_slug_collision_gets_numeric_suffix(self):
        BlogPost.objects.create(title="Hello World", excerpt="x", content="b")
        second = BlogPost.objects.create(title="Hello World", excerpt="y", content="b")
        self.assertEqual(second.slug, "hello-world-2")

    def test_existing_slug_preserved_on_title_change(self):
        post = BlogPost.objects.create(title="Original Title", excerpt="x", content="b")
        original_slug = post.slug
        post.title = "Completely Different Title"
        post.save()
        self.assertEqual(post.slug, original_slug)

    def test_blank_title_falls_back_to_post(self):
        post = BlogPost.objects.create(title="!!!", excerpt="x", content="b")
        self.assertTrue(post.slug.startswith("post"))
