# Generated by Django 5.2.7 on 2026-07-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_emailtemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unsubscribed", "Unsubscribed"),
                            ("bounced", "Bounced"),
                            ("manual", "Manual"),
                        ],
                        default="unsubscribed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
