# Generated by Django 5.2.7 on 2026-07-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_campaign_campaignrecipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignrecipient",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
