# Generated by Django 5.2.7 on 2026-07-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_alter_campaignrecipient_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignrecipient",
            name="claim_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
