# Generated by Django 5.2.7 on 2026-07-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0006_campaignrecipient_claim_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="body_source",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Authored HTML as edited. Sanitized but not CSS-inlined.",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="body_source",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Authored HTML as edited. Sanitized but not CSS-inlined.",
            ),
        ),
    ]
