# Generated by Django 5.2.7 on 2026-07-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0008_backfill_body_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignrecipient",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Not checked"),
                    ("valid", "Valid"),
                    ("invalid_syntax", "Malformed address"),
                    ("invalid_domain", "Domain has no mail server"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
