# Generated by Django 5.2.7 on 2026-07-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0009_campaignrecipient_validated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions",
                        to="messaging.campaign",
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "email")},
            },
        ),
    ]
