# Generated by Django 5.2.7 on 2026-08-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0010_campaignexclusion"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.EmailField(max_length=254)),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("body_plain", models.TextField(blank=True, default="")),
                ("body_html", models.TextField(blank=True, default="")),
                ("message_headers", models.JSONField(blank=True, default=dict)),
                ("attachments_info", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("archived", "Archived"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Inbound Email",
                "verbose_name_plural": "Inbound Emails",
                "ordering": ["-received_at"],
            },
        ),
    ]
