# Generated by Django 5.2.7 on 2026-09-27 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0011_inboundemail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mailbox", models.CharField(db_index=True, max_length=64)),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                (
                    "counterpart_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "counterpart_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("snippet", models.CharField(blank=True, default="", max_length=200)),
                ("unread", models.BooleanField(default=True)),
                ("archived", models.BooleanField(default=False)),
                ("last_message_at", models.DateTimeField(db_index=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Received"), ("out", "Sent")], max_length=3
                    ),
                ),
                ("from_name", models.CharField(blank=True, default="", max_length=200)),
                ("from_email", models.EmailField(max_length=254)),
                ("to", models.JSONField(blank=True, default=list)),
                ("cc", models.JSONField(blank=True, default=list)),
                (
                    "delivered_to",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("body_text", models.TextField(blank=True, default="")),
                ("body_html", models.TextField(blank=True, default="")),
                (
                    "message_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=500
                    ),
                ),
                (
                    "in_reply_to",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("references", models.TextField(blank=True, default="")),
                ("attachments", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_mail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messaging.mailthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
