# Generated by Django 5.2.7 on 2026-09-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0014_mail_spam_and_delete"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_daily_limit",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Recipients per person per day, unless overridden.",
                    ),
                ),
                (
                    "monthly_cap",
                    models.PositiveIntegerField(
                        default=3000,
                        help_text="Recipients the whole company may send per calendar month (staff mail and campaigns). Match it to the Mailgun plan.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Mail settings",
            },
        ),
    ]
