# Generated by Django 5.2.7 on 2026-09-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0015_mail_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="from_mailbox",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="campaign",
            name="note",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="campaign",
            name="send_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="message_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("delivered", "Delivered"),
                    ("bounced", "Bounced"),
                    ("complained", "Marked as spam"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaignrecipient",
            name="outcome_detail",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="body_html",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="suppression",
            name="reason",
            field=models.CharField(
                choices=[
                    ("unsubscribed", "Unsubscribed"),
                    ("bounced", "Bounced"),
                    ("complained", "Marked as spam"),
                    ("manual", "Manual"),
                ],
                default="unsubscribed",
                max_length=20,
            ),
        ),
    ]
