# Generated by Django 6.0 on 2026-07-20 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email Dispatch'), ('telegram', 'Telegram Webhook'), ('whatsapp', 'WhatsApp Notification'), ('dashboard', 'Editorial Dashboard')], default='dashboard', max_length=30)),
                ('recipient', models.CharField(default='editor@teklora.co.ke', max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='editorial.editorialarticle')),
            ],
        ),
    ]
