# Generated by Django 6.0 on 2026-07-20 19:42

import django.utils.timezone
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('doc_type', models.CharField(choices=[('article', 'Published Article'), ('research_dossier', 'Research Dossier'), ('trend_summary', 'Trend Summary'), ('source_doc', 'External Reference Document')], default='article', max_length=30)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Source URL, tags, category, author info')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
