# Generated by Django 5.2.7 on 2026-09-21 14:26

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="gemini", max_length=40)),
                ("model_id", models.CharField(max_length=120)),
                ("dimensions", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="building",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("status",),
                        name="only_one_active_embedding_space",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MemoryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(db_index=True, default="document", max_length=40),
                ),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("text", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "retrieval_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("last_retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("model_id", models.CharField(max_length=120)),
                ("dimensions", models.PositiveIntegerField()),
                ("vector", pgvector.django.vector.VectorField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="knowledge_base.embeddingspace",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="knowledge_base.memorydocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="memorydocument",
            index=models.Index(
                fields=["kind", "-retrieval_count"], name="knowledge_b_kind_7a4204_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="memorydocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_type__isnull", False)),
                fields=("content_type", "object_id"),
                name="one_memory_document_per_object",
            ),
        ),
        migrations.AddIndex(
            model_name="embedding",
            index=models.Index(
                fields=["space", "document"], name="knowledge_b_space_i_87d62e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="embedding",
            constraint=models.UniqueConstraint(
                fields=("space", "document"),
                name="one_embedding_per_document_per_space",
            ),
        ),
    ]
