# Generated by Django 6.0 on 2026-07-20 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('site_url', models.URLField(max_length=500)),
                ('feed_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='AI & Tech Media', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('timeframe', models.CharField(choices=[('next_month', 'Next Month'), ('next_quarter', 'Next Quarter'), ('next_year', 'Next Year')], default='next_quarter', max_length=20)),
                ('confidence_score', models.FloatField(default=0.7)),
                ('evidence_signals', models.JSONField(default=dict, help_text='GitHub stars, VC signals, search volume data')),
                ('prediction_report', models.TextField(help_text='Detailed AI forecasting report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_gap_score', models.FloatField(default=0.0, help_text='Opportunity score for Teklora')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='trends.competitorsource')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('keywords', models.JSONField(default=list, help_text='Extracted technology keywords')),
                ('source', models.CharField(help_text='e.g. Hacker News, GitHub Trending, Product Hunt, RSS', max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='Artificial Intelligence', max_length=100)),
                ('popularity_score', models.FloatField(default=0.0, help_text='Normalized 0-10 score')),
                ('growth_velocity', models.FloatField(default=0.0, help_text='Rate of mention growth')),
                ('future_potential', models.FloatField(default=0.0, help_text='Predicted long-term relevance')),
                ('confidence_score', models.FloatField(default=0.8, help_text='Source trustworthiness score')),
                ('novelty_score', models.FloatField(default=0.0)),
                ('business_relevance_score', models.FloatField(default=0.0)),
                ('african_relevance_score', models.FloatField(default=0.0)),
                ('developer_interest_score', models.FloatField(default=0.0)),
                ('virality_score', models.FloatField(default=0.0)),
                ('priority_score', models.FloatField(db_index=True, default=0.0, help_text='Weighted final decision score')),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('prioritized', 'Prioritized'), ('researching', 'Researching'), ('approved_for_article', 'Approved for Article'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='discovered', max_length=30)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
                'indexes': [models.Index(fields=['status', '-priority_score'], name='trends_tren_status_a3f9d9_idx'), models.Index(fields=['category'], name='trends_tren_categor_c01b0f_idx')],
            },
        ),
    ]
