# Generated by Django 5.2.7 on 2025-12-11 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('workflow_type', models.CharField(choices=[('chatbot', 'Chatbot Conversation'), ('blog_generation', 'Blog Generation'), ('content_enhancement', 'Content Enhancement')], default='chatbot', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_id', models.CharField(db_index=True, max_length=255)),
                ('state', models.JSONField()),
                ('checkpoint_metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ai_workflows.conversationcheckpoint')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='ai_workflows.conversationthread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(default='', max_length=100)),
                ('progress_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state', to='ai_workflows.conversationthread')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationthread',
            index=models.Index(fields=['thread_id'], name='ai_workflow_thread__55bbc8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationthread',
            index=models.Index(fields=['user', 'workflow_type'], name='ai_workflow_user_id_acc4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcheckpoint',
            index=models.Index(fields=['thread', 'checkpoint_id'], name='ai_workflow_thread__aea384_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcheckpoint',
            index=models.Index(fields=['thread', '-created_at'], name='ai_workflow_thread__d26910_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationcheckpoint',
            unique_together={('thread', 'checkpoint_id')},
        ),
    ]
