# Generated by Django 5.2.7 on 2026-09-21 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_workflows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvalRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What was being measured, e.g. 'baseline' or 'native-structured-output'.",
                        max_length=120,
                    ),
                ),
                (
                    "is_baseline",
                    models.BooleanField(
                        default=False,
                        help_text="The reference other runs are compared against.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("agents", models.JSONField(default=list)),
                ("samples_per_case", models.PositiveSmallIntegerField(default=1)),
                ("git_sha", models.CharField(blank=True, default="", max_length=40)),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="ai_workflow_started_167bd6_idx"
                    ),
                    models.Index(
                        fields=["is_baseline"], name="ai_workflow_is_base_0f8c60_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvalResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent", models.CharField(db_index=True, max_length=60)),
                ("case", models.CharField(max_length=120)),
                ("sample", models.PositiveSmallIntegerField(default=0)),
                ("grader", models.CharField(max_length=60)),
                ("score", models.FloatField(blank=True, null=True)),
                ("passed", models.BooleanField(null=True)),
                ("detail", models.TextField(blank=True, default="")),
                ("output", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ai_workflows.evalrun",
                    ),
                ),
            ],
            options={
                "ordering": ["agent", "case", "sample"],
                "indexes": [
                    models.Index(
                        fields=["run", "agent"], name="ai_workflow_run_id_b8f5bb_idx"
                    )
                ],
            },
        ),
    ]
