# Generated by Django 5.2.7 on 2026-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_workflows", "0002_evalrun_evalresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("step", models.CharField(db_index=True, max_length=120)),
                ("agent", models.CharField(blank=True, default="", max_length=60)),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Digest of the agent version that produced this.",
                        max_length=32,
                    ),
                ),
                ("value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["step", "-created_at"],
                        name="ai_workflow_step_d1723f_idx",
                    )
                ],
            },
        ),
    ]
