# Generated by Django 5.2.7 on 2026-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_workflows", "0003_stepresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_voice",
                    models.TextField(
                        default="Authoritative, forward-looking, technically grounded, African-centric, and accessible."
                    ),
                ),
                (
                    "preferred_terminology",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mappings such as {'AI': 'Artificial Intelligence'}.",
                    ),
                ),
                ("excluded_topics", models.JSONField(blank=True, default=list)),
                ("style_rules", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent profile",
                "verbose_name_plural": "Agent profile",
            },
        ),
    ]
