# Generated by Django 5.2.7 on 2026-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_workflows", "0005_seed_agent_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("absent", "No credential configured"),
                            ("candidate", "Credential present, not yet verified"),
                            ("active", "Verified"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                (
                    "billing",
                    models.CharField(
                        choices=[
                            ("usage", "Billed per token"),
                            ("subscription", "Consumes a subscription seat"),
                        ],
                        default="usage",
                        max_length=20,
                    ),
                ),
                ("preference", models.PositiveSmallIntegerField(default=100)),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Off keeps a provider out of resolution even with a valid key.",
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["preference", "name"],
            },
        ),
        migrations.CreateModel(
            name="CatalogueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=40)),
                ("model_id", models.CharField(max_length=200)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("context_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "input_price_per_mtok",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "output_price_per_mtok",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "price_source",
                    models.CharField(
                        choices=[
                            ("provider", "The provider's own API"),
                            ("openrouter", "Derived from OpenRouter's listing"),
                            ("manual", "Checked-in table"),
                            ("unknown", "Not known"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("price_checked_at", models.DateTimeField(blank=True, null=True)),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("deprecated_at", models.DateTimeField(blank=True, null=True)),
                ("available", models.BooleanField(default=True)),
                ("refreshed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Catalogue entries",
                "ordering": ["provider", "model_id"],
                "indexes": [
                    models.Index(
                        fields=["provider", "available"],
                        name="ai_workflow_provide_792200_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "model_id"),
                        name="one_catalogue_entry_per_model",
                    )
                ],
            },
        ),
    ]
