# Generated by Django 5.2.7 on 2026-09-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_workflows", "0006_provider_catalogueentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent", models.CharField(max_length=60, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("healthy", "Healthy"), ("failing", "Failing")],
                        default="healthy",
                        max_length=20,
                    ),
                ),
                (
                    "error_class",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("failing_since", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_alert_at", models.DateTimeField(blank=True, null=True)),
                ("suppressed_since_alert", models.PositiveIntegerField(default=0)),
                ("last_alert_error", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Agent health",
                "ordering": ["agent"],
            },
        ),
    ]
