# Generated by Django 5.2.7 on 2026-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_workflows", "0007_agenthealth"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="default_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which model to send chat requests to for this provider. Required: a provider with a working key and no chosen model is skipped, because picking one out of a five-hundred-row catalogue by heuristic is a guess whose wrong answers look exactly like its right ones. Gemini falls back to config.gemini_chat_model.",
                max_length=200,
            ),
        ),
    ]
