# Generated by Django 5.2.7 on 2026-09-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_workflows", "0008_provider_default_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="evalrun",
            name="provider_order",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
