# Generated by Django 5.2.7 on 2026-09-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_workflows", "0009_evalrun_provider_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelInvocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=40)),
                ("model_id", models.CharField(max_length=200)),
                (
                    "agent",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=60
                    ),
                ),
                ("role", models.CharField(blank=True, default="", max_length=20)),
                (
                    "label",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("run_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("reasoning_tokens", models.PositiveIntegerField(default=0)),
                ("cached_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Null when the model has no known price. Never zero for an unpriced call.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "price_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which authority the price came from, copied at call time.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="ai_workflow_created_3f5cb1_idx"
                    ),
                    models.Index(
                        fields=["agent", "-created_at"],
                        name="ai_workflow_agent_d82765_idx",
                    ),
                    models.Index(
                        fields=["provider", "-created_at"],
                        name="ai_workflow_provide_d84649_idx",
                    ),
                ],
            },
        ),
    ]
